import Head from 'next/head';
import EventList from '@/components/events/event-list';
import { getFeature } from '@/helper/api-utils';
import NewsletterRegistration from '@/components/input/newsletter-registration';

export async function getStaticProps() {
    const feature = await getFeature();
    return{
        props:{
            feature
        },
        revalidate: 1000
    }
}


export default function Home(props: any) {

  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div>
            <NewsletterRegistration />
            <EventList items={props.feature} />
        </div>
    </>
  )
}
